### ISSUE TITLE
Is there a solution for 3D printing shell

### ISSUE THREAD

**Issue by lonma** [timoknapp/rpi-nas#4]
Argon has launched a new raspberry pie shell Argon eon, but the crowdfunding price is a little expensive, is there a more cost-effective 3D printing solution, want to print a shell with board card deck nas
It is said that the hard disk connected to the raspberry pie USB interface through the USB cable can easily cause data damage, and the omv system does not support wireless access to the USB port. So I want to get a shell, a better group of nas for onboard interface.

**Comment by timoknapp** [comment]
Hi @lonma,

no unfortunately I am not aware of any solution based on a 3D printed shell. I was looking for it too, but could not find any similar solution. I know that using the USB ports for data transmission is not the best way possible but it worked quite well for me.

**Comment by timoknapp** [comment]
Closing this issue now
